---
runs:
  steps:
  - env:
      WORKFLOW_REF: '${{ github.workflow_ref }}'
    run: 'sh ${{ github.action_path }}/sh/get-workflow-path.sh'
    shell: 'sh'
  # - uses: actions/checkout@v4
  #   with:
  #     sparse-checkout: '${{ steps.get-workflow-path.outputs.workflow_path }}'
  #     sparse-checkout-cone-mode: false
  - env:
      GITHUB_WORKSPACE: '${{ github.workspace }}'
    run: 'sh ${{ github.action_path }}/sh/check-workflow.sh'
    shell: 'sh'
  using: 'composite'
...
