---
runs:
  steps:
  - env:
      WORKFLOW_REF: '${{ github.workflow_ref }}'
    id: 'get-workflow-path'
    run: 'sh ${{ github.action_path }}/sh/get-workflow-path.sh'
    shell: 'sh'
  - uses: actions/checkout@v4
    with:
      sparse-checkout: |
        ${{ steps.get-workflow-path.outputs.workflow_path }}
      sparse-checkout-cone-mode: false
  - env:
      ACTION_PATH: '${{ github.action_path }}'
      GITHUB_WORKSPACE: '${{ github.workspace }}'
      WORKFLOW_PATH: '${{ steps.get-workflow-path.outputs.workflow_path }}'
    run: 'sh ${{ github.action_path }}/sh/check-workflow.sh'
    shell: 'sh'
  using: 'composite'
...
