# check-workflow: exempt
---
inputs:
  action_path:
    description: 'github.action_path context for the action the workflow calls'
    required: true
runs:
  steps:
  - env:
      WORKFLOW_REF: '${{ github.workflow_ref }}'
    id: 'get-workflow-path'
    run: 'sh ${{ github.action_path }}/sh/get-workflow-path.sh'
    shell: 'sh'
  - uses: 'actions/checkout@v4'
    with:
      path: 'check-workflow'
      sparse-checkout: |
        ${{ steps.get-workflow-path.outputs.workflow_path }}
      sparse-checkout-cone-mode: false
  - env:
      ACTION_PATH: '${{ inputs.action_path }}'
      CHECKOUT_WORKSPACE: '${{ github.workspace }}/check-workflow'
      WORKFLOW_PATH: '${{ steps.get-workflow-path.outputs.workflow_path }}'
    run: 'sh ${{ github.action_path }}/sh/check-workflow.sh'
    shell: 'sh'
  using: 'composite'
...
