---
inputs:
  action_path:
    required: true
    description: 'github.action_path context for the action the workflow calls'
runs:
  steps:
  - run: 'echo "::group::Check workflow"'
    shell: 'sh'
  - env:
      WORKFLOW_REF: '${{ github.workflow_ref }}'
    id: 'get-workflow-path'
    run: 'sh ${{ github.action_path }}/sh/get-workflow-path.sh'
    shell: 'sh'
  - uses: actions/checkout@v4
    with:
      sparse-checkout: |
        ${{ steps.get-workflow-path.outputs.workflow_path }}
      sparse-checkout-cone-mode: false
  - env:
      ACTION_PATH: '${{ inputs.action_path }}'
      GITHUB_WORKSPACE: '${{ github.workspace }}'
      WORKFLOW_PATH: '${{ steps.get-workflow-path.outputs.workflow_path }}'
    run: 'sh ${{ github.action_path }}/sh/check-workflow.sh'
    shell: 'sh'
  - run: 'echo "::endgroup::"'
    shell: 'sh'
  using: 'composite'
...
