---
author: 'Econia Labs'
description: 'Require extra approvals for PRs with many lines added/removed.'
inputs:
  github_token:
    description: 'GitHub token for API access.'
    required: true
  max_lines_added:
    description: 'Maximum lines that can be added before requiring override.'
    required: true
  max_lines_removed:
    description: 'Maximum lines that can be removed before requiring override.'
    required: true
  n_override_approvals:
    description: 'Number of approvals required for override.'
    required: true
name: 'PR size'
runs:
  steps:
  - uses: 'actions/checkout@v4'
    with:
      fetch-depth: 0
      token: '${{ inputs.github_token }}'
  - run: 'echo ${{ inputs.max_lines_added }}'
    shell: 'sh'
  - run: 'echo ${{ inputs.max_lines_removed }}'
    shell: 'sh'
  - run: 'echo ${{ inputs.n_override_approvals }}'
    shell: 'sh'
  using: 'composite'
...
