---
author: 'Econia Labs'
description: 'Require extra approvals for PRs with many lines added/removed'
inputs:
  max_lines_added:
    description: 'Maximum lines that can be added before requiring override'
    required: true
  max_lines_removed:
    description: 'Maximum lines that can be removed before requiring override'
    required: true
  n_override_approvals:
    description: 'Number of approvals required for override'
    required: true
name: 'PR size'
runs:
  steps:
  - uses: 'actions/checkout@v4'
    with:
      fetch-depth: 0
  - env:
      GITHUB_EVENT_NAME: '${{ github.event_name }}'
    id: 'check-if-in-merge-group'
    run: 'sh ${{ github.action_path }}/sh/check-if-in-merge-group.sh'
    shell: 'sh'
  - env:
      PR_NUMBER: '${{ github.event.pull_request.number }}'
    id: 'get-pr-number'
    run: 'sh ${{ github.action_path }}/sh/get-pr-number.sh'
    shell: 'sh'
  - env:
      GH_TOKEN: ${{ github.token }}
      PR_NUMBER: '${{ steps.get-pr-number.outputs.number }}'
    id: 'get-base-branch'
    run: 'sh ${{ github.action_path }}/sh/get-base-branch.sh'
    shell: 'sh'
  - env:
      BASE_BRANCH: '${{ steps.get-base-branch.outputs.base_branch }}'
    id: 'get-n-lines-added'
    run: 'sh ${{ github.action_path }}/sh/get-n-lines-added.sh'
    shell: 'sh'
  - env:
      BASE_BRANCH: '${{ steps.get-base-branch.outputs.base_branch }}'
    id: 'get-n-lines-removed'
    run: 'sh ${{ github.action_path }}/sh/get-n-lines-removed.sh'
    shell: 'sh'
  using: 'composite'
...
