---
jobs:
  check-pr-size:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'econia-labs/common/.github/actions/pr-size@ECO-2962'
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        max_lines_added: '${{ vars.PR_SIZE_MAX_LINES_ADDED }}'
name: 'Check PR Size'
'on':
  pull_request: null
  pull_request_review: null
  workflow_dispatch: null
...
